# Generated by Django 5.0.6 on 2024-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_ficha',
            field=models.IntegerField(default=0),
        ),
    ]
